### ISSUE TITLE
Assorted minor bugs

### ISSUE THREAD

**Issue by semisight** [handldigital/gtm-utmsimple#1]
https://github.com/handldigital/gtm-utmsimple/blob/9646109a299a1b6aad2674088fdf810fc964492c/template.tpl#L73

`customParams` is never actually used? Did you intend to use it? If not, consider removing.

https://github.com/handldigital/gtm-utmsimple/blob/9646109a299a1b6aad2674088fdf810fc964492c/template.tpl#L77

It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

https://github.com/handldigital/gtm-utmsimple/blob/9646109a299a1b6aad2674088fdf810fc964492c/template.tpl#L83-L84

Please remove.

https://github.com/handldigital/gtm-utmsimple/blob/9646109a299a1b6aad2674088fdf810fc964492c/template.tpl#L87

Typo? Extraneous `8` at the end of the log string.

https://github.com/handldigital/gtm-utmsimple/blob/9646109a299a1b6aad2674088fdf810fc964492c/template.tpl#L92-L93

Please remove.

https://github.com/handldigital/gtm-utmsimple/blob/9646109a299a1b6aad2674088fdf810fc964492c/template.tpl#L94

Please uncomment this line. `gtmOnSuccess` is needed for tags to run correctly.

**Comment by haktan-suren** [comment]
thanks for the review @semisight 

Your recommendations have been considered and implemented except the customParams as customParams is an optional global variable for our plugin. If it is defined, it will be used.

**Comment by semisight** [comment]
For the `encodeUriComponent` call, you'll need to add

```javascript
const encodeUriComponent = require('encodeUriComponent');
```

at the top.

Also, is this still needed?

https://github.com/handldigital/gtm-utmsimple/blob/276e84407ea7d7760861f0fd226261aa02d58cb8/template.tpl#L80-L82

**Comment by haktan-suren** [comment]
> For the `encodeUriComponent` call, you'll need to add
> 
> ```js
> const encodeUriComponent = require('encodeUriComponent');
> ```
> 
> at the top.
Done. 

> 
> Also, is this still needed?
> 
> https://github.com/handldigital/gtm-utmsimple/blob/276e84407ea7d7760861f0fd226261aa02d58cb8/template.tpl#L80-L82
I removed it for now, we'll use it in future releases.

**Comment by haktan-suren** [comment]
@semisight , any update on this?

**Comment by semisight** [comment]
Hi @haktan-suren, I apologize for leaving this for so long. Some of my notifications got lost at the bottom of the queue in Github :(

Your `1be3fab` release looks good to me, you just need to update your metadata.yaml file and I can merge this into the gallery.

**Comment by haktan-suren** [comment]
Thanks @semisight 

Just updated it on master. Looking forward to hearing from you.

**Comment by haktan-suren** [comment]
@semisight bumping this up for you

**Comment by haktan-suren** [comment]
@semisight bumping this again...
